[[datasources]]
== Available DataSources

Multiple DataSource implementations are provided in accordance with the JDBC specification. Each implementation
provides specific capabilities and is intended to be used for a specific purpose.


=== Standard DataSource
[source,java]
----
com.impossibl.postgres.jdbc.PGDataSource
----

Basic DataSource implementation that provides similar functionality to that of connections vended by the Driver
implementation.

This DataSource can be used as a convenience or when a DataSource is required but neither connection pooling
or XA capabilities are also required.


=== Connection Pool DataSource
[source,java]
----
com.impossibl.postgres.jdbc.PGConnectionPoolDataSource
----

The pooling DataSource provides connections that can be reused. Reuse avoids costly connection time and
increases performance.

TIP: Although `PGConnectionPoolDataSource` is a convenient and compliant implementation of JDBC's
`javax.sql.ConnectionPoolDataSource`, using a library specifically built to support JDBC connection pooling, in
conjunction with `PGDataSource`, will most likely yield better performance.


=== XA DataSource
[source,java]
----
com.impossibl.postgres.jdbc.xa.PGXADataSource
----

DataSource with XA support for prepared transactions and two phase commit.

NOTE: Full usage of the XA capabilities provided by this DataSource require the presence of a compliant
JTA transaction manager.
