[[logging-tracing]]
== Logging & Tracing

[[logging]]
=== Logging
{drivername} uses the Java platform's `java.util.logging` API for all of its logging.

==== Configuration
The logging configuration is done using the standard `java.util.logging` configuration method using a
`logging.properties` file.

The root logging package is `com.impossibl.postgres`, configuration of this package will control all log
messages generated by {drivername}.

TIP: {drivername} uses logging specifically for configuration, warnings, errors and intermittent informational
messages. For more detailed inspection of the drivers activities and state, <<tracing>> is provided.

[[tracing]]
=== Tracing

{drivername} provides tracing to diagnose errors and performance problems that may arise while using connections
provided by the Driver or one of the DataSources. Tracing is managed separately from logging to allow generation
of succinct trace logs that are easy to ready, unlike logging which can be extremely verbose.

There are *three* distinct levels of tracing provided by {drivername} to allow inspection of specific activities
of the Driver, DataSources and Connections.

[[tracing-jdbc]]
==== JDBC API Level

The JDBC API tracing provides a trace log of all user generated JDBC API calls; it specifically excludes
any calls the driver itself may make to public JDBC API. This allows investigation of what, specifically, the
driver is being asked to execute.

Each trace log entry includes the name of the API method called, all parameters (along with documentation level
names and their provided values), as well as the return value of the method.

API tracing is enabled with the `api.trace` & `api.trace.file` settings. See <<connection-settings>>.

API tracing is built using the <<spy>> library provided by the {drivername} project as well.

[[tracing-sql]]
==== SQL Level

SQL tracing provides a trace log of all SQL passed to the server. It is useful in determining what exactly
is sent to the server and in what order.

To honor the JDBC specification the {drivername} sometimes manipulates user provided SQL by prepending/appending
text, replacing "escapes" and more. In addition to this manipulation, sometimes SQL is generated and executed on
behalf of the user (e.g. `COMMIT` & `ROLLBACK`). All of this is manipulation and generating is done _before_ the
SQL trace log, therefore it provides a log of exactly what SQL is sent to the server to be executed.

Each trace log entry includes the SQL to be executed by the server as well as what operation the server is being
requested, including "preparing" SQL for execution, executing previously prepared SQL and directly executing
unprepared SQL.

SQL tracing is enabled with the `sql.trace` & `sql.trace.file` settings. See <<connection-settings>>.

[[tracing-protocol]]
==== Protocol Level

Protocol level tracing provides a WireShark _inspired_ trace log of all {vendorname} Frontend/Backend protocol
messages passed betweeen {drivername} and the connected server.

This trace log is very compact but provides message IDs, message direction and dispatch information for all
communication with the server.

NOTE: Protocol tracing is a valuable resource for low-level driver debugging but is not much use for
those who are not familiar with the underlying {vendorname} protocol; almost everybody should stick to
JDBC & SQL level tracing.

Protocol tracing is enabled with the `protocol.trace` & `protocol.trace.file` settings. See <<connection-settings>>.
