:jdbc-driver-type4: https://en.wikipedia.org/wiki/JDBC_driver#Type_4_driver_–_Database-Protocol_driver_(Pure_Java_driver)
:maven-central: http://oss.sonatype.org/service/local/artifact/maven/redirect

[[overview]]
== Overview

The goal of this document is to provide an easy path to start using {drivername} for those people looking for
a JDBC compliant driver for {vendorname}. It also aims to provide detailed reference documentation for those
wishing to use the advanced features of JDBC integrated with {vendorname}.

[[overview-what-is]]
=== What is {drivername}?

{drivername} aims to be a fully compliant JDBC driver for {vendorname}, implementing JDBC 4.2 onwards.
The major goal of the project is to implement all the advanced features of JDBC also supported in
{vendorname}; including composite types, arrays of primitive and composite types, asynchronous
notifications, and more.

[[overview-java-versions]]
=== Supported Java Versions

{drivername} requires Java 8 (or higher) which equates to the JDBC 4.2 specification. Support for Java 9's
JDBC 4.3 is forthcoming and will be backwards compatible.

[[overview-getting-started]]
=== Getting Started


[[overview-getting-started-deps]]
==== Dependencies

To use the JDBC Driver or DataSource implementation you'll need to add the dependencies to your project or classpath.

===== Maven Style Dependencies

Adding the driver to a project built with a tool that supports maven style dependencies (e.g. Maven, Gradle, Ivy,
 etc.) only requires adding the primary dependency to your build file.

====== Maven
For Maven simply add the dependency to your `pom.xml`

[source,xml,subs="attributes+"]
----
<dependency>
    <groupId>{driverdepgroup}</groupId>
    <artifactId>{driverdepname}</artifactId>
    <version>{driverdepver}</version>
</dependency>
----

====== Gradle
For Gradle the dependency is added to your `build.gradle`

[source,groovy,subs="attributes"]
----
dependencies {
    compile "{driverdepgroup}:{driverdepname}:{driverdepver}"
}
----

NOTE: Using these artifacts will pull in the driver implementation and its required dependencies. If you wish
to depend on a version of the driver that embeds its dependencies you can use the artifact name
`{driverdepname}-{driverdepver}-{uberclass}` instead; this is useful to work around dependency conflicts in certain
situations but otherwise should not be necessary.

[[overview-getting-started-download]]
===== Manual Download

If you are using a project that does not support Maven style dependencies or you wish to add the driver globally to
an application server like Glassfish, <<appservers-wildfly>> or Tomcat you can download the dependency embedded
version of the driver and copy it to the location required by your project or usage.

{maven-central}?r={mavenrepo}&g={driverdepgroup}&a={driverdepname}&c={uberclass}&v={driverdepver}[Download JAR]


[[overview-getting-started-connect]]
==== Connecting to {vendorname}

To connect to a {vendorname} server with {drivername} you need to use one of its implementation of JDBC's
`java.sql.Driver` or `javax.sql.DataSource` interface.  Each method has its own use cases and connection
 routine.

[[overview-getting-started-connect-driver]]
===== Using the JDBC Driver

The simplest way to obtain a connection is by using the `java.sql.Driver` implementation and only
 requires a properly constructed URL along with a call to `java.sql.DriverManager`.

[source,java]
----
String url = "jdbc:pgsql://localhost/test";  <1>
String user = "test";
String password = "test";
Connection connection = DriverManager.getConnection(url, user, password); <2>
----
<1> `pgsql` requests a {drivername} connection to the server listening on `localhost`
    using the default port `5432` and targeting the `test` database.
<2> Opens a connection to the {vendorname} server.

The URL provided in the example above is one of the simplest URLs required to make a connection. The
full URL format accepts credentials, connection settings, fallback hosts and more. <<connection-urls>>
provides details about the extended format of URLs accepted by the driver.


[[overview-getting-started-connect-ds]]
===== Using the JDBC DataSource

While using the Driver implementation can be the easiest way to connect to a server, using a
`javax.sql.DataSource` implementation can allow using enhanced features such as connection pooling
and XA transactions.

Obtaining a connection using one of the DataSource implementations is done by explicitly
 creating an instance of the DataSource and acquiring connections from it.

[source,java]
----
PGDataSource ds = new PGDataSource(); <1>
ds.setServerName("localhost"); <2>
ds.setDatabaseName("test"); <3>
ds.setUser("test"); <4>
ds.setPassword("test");

Connection connection = ds.getConnection(); <5>
----
<1> Creates a new instance of the standard DataSource implementation.
<2> Sets the target of the connection to `localhost`
<3> Sets the target database to `test`
<4> Set the user & password credentials to connect with.
<5> Opens a connection to the {vendorname} server.

While the example uses the basic implementation of DataSource, there are a couple of implementations
to choose from detailed in <<datasources>>.

Only the most basic properties on the DataSource implementations are demonstrated. The DataSource
provides properties for all of the settings available that control almost every aspect of vended
connections. Details of all setting available for connections is detailed in <<connection-settings>>.

NOTE: Alternatively to setting individual properties as shown above, the DataSource also accepts a
connection URL like the one shown in <<overview-getting-started-connect-driver>> and detailed in
<<connection-urls>>.
