#!/bin/sh
set -x
set -e

openssl aes-256-cbc -K ${encrypted_14b7f04d1600_key} -iv ${encrypted_14b7f04d1600_iv} -in .travis/github_deploy_key.enc -out .travis/github_deploy_key -d

chmod 600 .travis/github_deploy_key

eval "$(ssh-agent -s)"

ssh-add .travis/github_deploy_key
