#!/bin/sh
set -x
set -e

SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"

openssl aes-256-cbc -K ${encrypted_14b7f04d1600_key} -iv ${encrypted_14b7f04d1600_iv} -in .travis/github_deploy_key.enc -out "$SSH_FILE" -d

chmod 600 "$SSH_FILE"
printf "%s\n" "Host github.com  IdentityFile $SSH_FILE  LogLevel ERROR" >> ~/.ssh/config

eval "$(ssh-agent -s)"

ssh-add "$SSH_FILE"
